package com.example.compose
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF005FCC) // A nice medium blue
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD6E2FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001A43)
val md_theme_light_secondary = Color(0xFF006E8A) // A teal blue
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFB3E7FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001F28)
val md_theme_light_tertiary = Color(0xFF745BFF) // A periwinkle blue
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEADDFF)
val md_theme_light_onTertiaryContainer = Color(0xFF23005D)
val md_theme_light_error = Color(0xFFBA1B1B) // Keeping error color
val md_theme_light_errorContainer = Color(0xFFFFDAD4)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFFCFCFF) // A light blue-white
val md_theme_light_onBackground = Color(0xFF001933) // Very dark blue for text
val md_theme_light_surface = Color(0xFFFCFCFF) // A light blue-white
val md_theme_light_onSurface = Color(0xFF001933) // Very dark blue for text
val md_theme_light_surfaceVariant = Color(0xFFDCE4F2) // Light blue-grey
val md_theme_light_onSurfaceVariant = Color(0xFF404859) // Dark blue-grey
val md_theme_light_outline = Color(0xFF717C8B)
val md_theme_light_inverseOnSurface = Color(0xFFEFF3FF) // Very light blue
val md_theme_light_inverseSurface = Color(0xFF30415D) // Dark blue
val md_theme_light_inversePrimary = Color(0xFFB3C6FF) // Light blue
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF005FCC)

val md_theme_dark_primary = Color(0xFFB3C6FF) // Light blue
val md_theme_dark_onPrimary = Color(0xFF003366) // Dark blue
val md_theme_dark_primaryContainer = Color(0xFF004B99) // Medium blue
val md_theme_dark_onPrimaryContainer = Color(0xFFD6E2FF)
val md_theme_dark_secondary = Color(0xFF4FD3DE) // Cyan
val md_theme_dark_onSecondary = Color(0xFF00363D) // Dark blue-green
val md_theme_dark_secondaryContainer = Color(0xFF005058) // Deep teal
val md_theme_dark_onSecondaryContainer = Color(0xFFB3E7FF)
val md_theme_dark_tertiary = Color(0xFFD1C4FF) // Lavender
val md_theme_dark_onTertiary = Color(0xFF3A007D) // Deep purple
val md_theme_dark_tertiaryContainer = Color(0xFF4E33A8) // Purple
val md_theme_dark_onTertiaryContainer = Color(0xFFEADDFF)
val md_theme_dark_error = Color(0xFFFFB4AB) // Light red
val md_theme_dark_errorContainer = Color(0xFF93000A) // Dark red
val md_theme_dark_onError = Color(0xFF680003) // Darker red
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD4)
val md_theme_dark_background = Color(0xFF001933) // Very dark blue
val md_theme_dark_onBackground = Color(0xFFE0E3FF) // Light blue
val md_theme_dark_surface = Color(0xFF001933) // Very dark blue
val md_theme_dark_onSurface = Color(0xFFE0E3FF) // Light blue
val md_theme_dark_surfaceVariant = Color(0xFF404859) // Dark blue-grey
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C9D4) // Light blue-grey
val md_theme_dark_outline = Color(0xFF8E95A3)
val md_theme_dark_inverseOnSurface = Color(0xFF001933) // Very dark blue
val md_theme_dark_inverseSurface = Color(0xFFE0E3FF) // Light blue
val md_theme_dark_inversePrimary = Color(0xFF005FCC) // Medium blue
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFB3C6FF) // Light blue

val seed = Color(0xFF005FCC) // Medium blue as a seed color
